database:
  image: mysql:5.7
  restart: always
  ports:
    - "8081:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=database
    - MYSQL_USER=username
    - MYSQL_PASSWORD=password
  volumes:
    - ./database/storage:/var/lib/mysql
    - ./database/initdb.d/01-dump.sql:/docker-entrypoint-initdb.d/01-dump.sql
webserver:
  build: ./webserver
  restart: always
  links:
    - database
  ports:
    - "8080:80"
  volumes:
    - ./webserver/config/php/php.ini:/usr/local/etc/php/php.ini
    - ./webserver/config/apache/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
    - ./webserver/www:/var/www/html
